### ISSUE TITLE
Rückgabewert für wind_gust bei fehlenden Daten

### ISSUE THREAD

**Issue by Morg42** [jentz1986/shng-owm-plugin#3]
Wenn wind_gust nicht geliefert wird, sollte entweder ein "ungültig"-Wert (zB -1) oder der aktuelle wind-Wert zurückgegeben werden, nicht eine Info geloggt.

(siehe https://knx-user-forum.de/forum/supportforen/smarthome-py/1246998-support-thread-zum-openweathermap-plugin?p=1695381#post1695381)

**Comment by jentz1986** [comment]
So, worüber konfiguriert ein User nun folgendes dictionary?

        self._soft_fails = {
            "rain/1h": "number=0",
            "rain/3h": "number=0",
            "snow/1h": "number=0",
            "snow/3h": "number=0",
            "rain/": "number=0",
            "snow/": "number=0",
            "wind_gust/": "relative=../wind_speed",
            "wind_gustav/": "number=-1",
            "wind_gustavs/": "string=-1",
            "wind_gustavn/": "no_update",
            "wind_gustavi/": "log_info"
        }

**Comment by jentz1986** [comment]
OK, habs jetzt einfach in Plugin-Parameter ausgelagert.
